# Generated by Django 4.2.6 on 2023-11-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_cpf_alter_perfil_idade_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular'),
        ),
    ]
