# Generated by Django 4.2.6 on 2023-11-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_remove_perfil_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
