# Generated by Django 4.2.6 on 2023-11-16 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_perfil_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Número de telefone deve estar no formato internacional. Exemplo: +123456789', regex='^\\+?1?\\d{9,15}$')], verbose_name='Nº telefone celular'),
        ),
    ]
